### ISSUE TITLE
 Juspay Developer company image is not visible (temporary issue)

### ISSUE THREAD

**Issue by anuza08** [GrabBits/GrabBits_Website#10]
![Screenshot (11)](https://github.com/GrabBits/GrabBits_Website/assets/98256478/e9d74f06-d32d-422f-a6a8-5abb3e02d135)

Please allow me to solve this issue.

**Comment by Spyware007** [comment]
@anuza08 That's the problem with the backend.
We had fixed that already.
Thanks.
You can create another issue.
