### ISSUE TITLE
Unexpected behavior of Search Bar

### ISSUE THREAD

**Issue by Shashank2104125** [GrabBits/GrabBits_Website#106]
**Describe the bug**
Even after entering the data while removing the cursor from it search bar will back to it's original state.

**Location of the bug**
http://localhost:3000/opportunities

**Expected behavior**
If the user enters data until and unless data is there it will be in an expanded state.

**Screenshots/Video**

https://github.com/GrabBits/GrabBits_Website/assets/97789487/37ff812d-16e3-4ac5-9fd3-7a519fa55bda

**Comment by ritik48** [comment]
I would  like to work on this issue under GSSoC'23

**Comment by kuvamdazeus** [comment]
Assigned this issue to @Shashank2104125 

@ritik48 please find or create another issue to work on for now :)
