### ISSUE TITLE
Company logo not displaying in opportunities section

### ISSUE THREAD

**Issue by Yashika-Agrawal** [GrabBits/GrabBits_Website#114]
**Describe the bug**
Company logo not displaying in opportunities section , image link not working

**Location of the bug**
In opportunities section , juspay developer hiring challenge.

**Expected behavior**
Properly aligned company logo will display in Juspay developer hiring challenge.

**Screenshots**
![image](https://github.com/GrabBits/GrabBits_Website/assets/97408966/d2456a55-1c73-4202-b903-491fb6b45223)

**Comment by Yashika-Agrawal** [comment]
Hay , I am a GSsoc'23 contributor assign me this issue.

**Comment by Spyware007** [comment]
@Yashika-Agrawal That is a backend problem, its already solved!
