### ISSUE TITLE
Opportunities and Podcast page style improvement

### ISSUE THREAD

**Issue by ojasaklechayt** [GrabBits/GrabBits_Website#115]
### What's the style idea?

I have done some changes in Opportunities page and Podcast page.
The website looks almost perfect. So, to make it even better, I have done these changes.

1. Opportunities Page -
     Added gapping between cards
     Added poppins as a font because that looks better than the previous once
     Changed button gapping 
2. Podcast Page -
     Changed button gapping 

So, can you please assign this to me under gsocc23 ?

### Add screenshots

Before -

![image](https://github.com/GrabBits/GrabBits_Website/assets/90605717/61fa2cdf-d6e5-4b96-a7da-a49c9a0c58fb)

![image](https://github.com/GrabBits/GrabBits_Website/assets/90605717/225b9548-4e9c-496a-bb0b-45324ba7f75d)

After - 

![image](https://github.com/GrabBits/GrabBits_Website/assets/90605717/4ef47dce-f418-4c29-8b5e-50391e7d0d1e)

![image](https://github.com/GrabBits/GrabBits_Website/assets/90605717/a489008d-a114-4548-988b-8ba47280d6d5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ojasaklechayt** [comment]
@kuvamdazeus

**Comment by Bhushan8177** [comment]
@ojasaklechayt you can join our discord server for any help required !!

**Comment by Bhushan8177** [comment]
The above UI looks perfect , you can start implementing , Assigning you !!
