### ISSUE TITLE
Image and navbar are not showing in website

### ISSUE THREAD

**Issue by vk20july** [GrabBits/GrabBits_Website#120]
**Describe the bug**
The image of justpay developer hiring challenge is not showing and navbar also not showing in opportunities page.

**Screenshots**
![Screenshot (208)](https://github.com/GrabBits/GrabBits_Website/assets/71543332/c5c725cb-f38d-418e-97da-99288ccfd8d4)

**Comment by Bhushan8177** [comment]
hey @vk20july , the image is not showing because of the format ig, can you fix that ? I can assign if you are ready !!

**Comment by vk20july** [comment]
yes sir

**Comment by vk20july** [comment]
@Bhushan8177 ye image aapne mongodb(backend) me store kiya hua hai mujhe uska link milega 
because apne frontend me toh iske images upload nhi kiya hai
