### ISSUE TITLE
Search bar over the NavBar

### ISSUE THREAD

**Issue by shobhitexe** [GrabBits/GrabBits_Website#121]
**Describe the bug**
When going [here](https://grabbits.vercel.app/opportunities) the search bar is overflowing the Navbar as seen in attcahed SS

**Location of the bug**
https://grabbits.vercel.app/opportunities

**Expected behavior**
It should not overflow into the navbar even i didnt click search then also its like this 

**Screenshots**
![image](https://github.com/GrabBits/GrabBits_Website/assets/29349136/37fc8d2c-a578-4945-86ad-6794193a6238)

**Comment by shobhitexe** [comment]
https://github.com/GrabBits/GrabBits_Website/assets/29349136/828b88e0-5348-4278-932a-5f59a0f464f6

screen record of the issue

**Comment by Bhushan8177** [comment]
Great observation @shobhitexe , Assigning it to you Best of luck !!
