### ISSUE TITLE
[bug] : page does not redirect to the top on click in mobile view

### ISSUE THREAD

**Issue by Princeton21** [GrabBits/GrabBits_Website#126]
**Describe the bug**

In mobile view, on clicking the links in the navbar, the page is not redirecting to the top of the page and is stuck on the footer component.

**Location of the bug**
Navbar component

**Screenshots**

https://github.com/GrabBits/GrabBits_Website/assets/77603501/328fa62d-9691-4b96-900c-ebc69b31418b

Kindly assign this issue to me
I would like to work on it

**Comment by Bhushan8177** [comment]
Great observation @Princeton21 🫂, assigning it to you , go ahead!!
