### ISSUE TITLE
[bug] : Footer section Instagram link is not working

### ISSUE THREAD

**Issue by CYBWEBALI** [GrabBits/GrabBits_Website#132]
**Describe the bug**

In Footer section, Instagram Link is not working and on click it is showing no profile found.

**Screenshots**
![image](https://github.com/GrabBits/GrabBits_Website/assets/88965204/9c3f877f-e015-4f77-a542-e429f8c46155)
![image](https://github.com/GrabBits/GrabBits_Website/assets/88965204/3fd621ea-9cc6-4562-917e-da5fc79d006e)

**Comment by CYBWEBALI** [comment]
Hey,If you can provide me your Instagram handle link I can fix this.

**Comment by Bhushan8177** [comment]
hey @CYBWEBALI , can you post a video of the same because it is working fine on mine !!

**Comment by CYBWEBALI** [comment]
This issue has been fixed now.
