### ISSUE TITLE
Search Tab Hover Bug

### ISSUE THREAD

**Issue by ojasaklechayt** [GrabBits/GrabBits_Website#134]
**Describe the bug**
There is a extended div which is to be there when we hover on the search button. And when there is no hovering, it went to the navbar creating error.

**Location of the bug**
Opportunity page

**Expected behavior**
No hover tab at navbar

**Screenshots**

Before:
![image](https://github.com/GrabBits/GrabBits_Website/assets/90605717/ce5dc0f4-8591-4247-b73e-044d1302abae)

After:
![image](https://github.com/GrabBits/GrabBits_Website/assets/90605717/93647607-a7cb-405e-b05e-68ce834cb734)

**Additional context**
display: none tag was commented which is to be uncommented

**Comment by Bhushan8177** [comment]
Hey @ojasaklechayt , this issue has already been solved, thank you for your contribution 🤩
