### ISSUE TITLE
Invalid email is accepting

### ISSUE THREAD

**Issue by dipakja** [GrabBits/GrabBits_Website#136]
**Describe the bug**
In the contact section, the form is taking invalid data. For e.g. email address

**Location of the bug**
In the contact us section

**Expected behavior**
It should show invalid data or invalid email address after we put the invalid data or email address.

![grabit](https://github.com/GrabBits/GrabBits_Website/assets/104189165/6ebb499f-abea-41c7-9a7b-a68d857085b6)

**Comment by kuvamdazeus** [comment]
Hey @dipakja

A a similar issue was assigned to someone else for contact form validation (#133)
Please find or create another issue :)
