### ISSUE TITLE
[style]: Overflow of box in the website

### ISSUE THREAD

**Issue by HimanshuNarware** [GrabBits/GrabBits_Website#137]
### What's the style idea?

We need to improve the find/Your dream job. In your section box, the 4 number in the website is overflowing from the parent container, I want to resolve this issue in the website kindly assign me this issue.

### Add screenshots

Add screenshots
![133](https://github.com/GrabBits/GrabBits_Website/assets/83147410/c0d901f0-dbb5-4a90-9de8-31bef67ae4a0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kuvamdazeus** [comment]
Actually, @HimanshuNarware it is the design of the website.
But if you'd like to contribute towards the design of the landing page,

You can collaborate on issue #135

Closing this issue for now, please feel free to create a new issue :)
