### ISSUE TITLE
[FEAT] ADD MISSING ICONS FOR UNSDG GOALS

### ISSUE THREAD

**Issue by Monson2002** [GrabBits/GrabBits_Website#140]
**Is your feature request related to a problem? Please describe.**
In the README file, in "Our Goals" section, icons for UN goal no. 8 and 10 are missing.

**Describe the solution you'd like**
This could be solved by adding the icon images to the README file by me.

**Before**
<img width="958" alt="old" src="https://github.com/GrabBits/GrabBits_Website/assets/91113152/a5b7d7d8-a7ac-4afd-97f9-253290a4daca">

**After**
<img width="953" alt="new" src="https://github.com/GrabBits/GrabBits_Website/assets/91113152/61bcc396-eea8-455e-b728-3239c1ccb5ce">

**Comment by Bhushan8177** [comment]
For the moment I don't think it's necessary @Monson2002 , you can go for other issues 🚀🔥
