### ISSUE TITLE
PR Template in .yml format

### ISSUE THREAD

**Issue by ManasMadan** [GrabBits/GrabBits_Website#142]
Pull Request Template means when someone opens a Pull Request, they will have a template that they can edit making it easier for maintainers of the project to review PR and make sure that no PR is submitted without proper description.

**Comment by ManasMadan** [comment]
@kuvamdazeus Please assign me this under GSSoC 23

**Comment by Bhushan8177** [comment]
Assigned @ManasMadan , Go ahead!!

**Comment by ManasMadan** [comment]
@Bhushan8177 have created a PR #147 Merging that closes this issue
