### ISSUE TITLE
Adding Testimonial Section

### ISSUE THREAD

**Issue by abhi03ruchi** [GrabBits/GrabBits_Website#145]
**Is your feature request related to a problem? Please describe.**

I would like to create Testimonial Section for the website.
The testimonial section on the website will provide a valuable advantage in showcasing positive experiences and feedback from satisfied individuals.
 By featuring testimonials, a website gains the advantage of instilling trust, attracting new people, and reinforcing the reputation of the brand. It creates a sense of authenticity and reliability, ultimately leading to increased confidence and a higher likelihood of conversions.

**Describe the solution you'd like**
I will add a carousel containing testimonials of individuals.

**Additional context**
Plz, assign this task to me under gssoc'23.

**Comment by Bhushan8177** [comment]
Can you specify the style of carousal you are planning to implement, will check if it's fit within the theme of the project!!

**Comment by abhi03ruchi** [comment]
<img width="1118" alt="Screenshot 2023-06-04 at 3 52 06 PM" src="https://github.com/GrabBits/GrabBits_Website/assets/105661636/5e066b1b-473a-4c18-af1f-d665ceccc2eb">
automatic changing Carousel ,

**Comment by Bhushan8177** [comment]
I guess we can make it look more cool , what do you say !!

**Comment by Spyware007** [comment]
@abhi03ruchi Assigned to you!
All the best!

**Comment by Deepanshu0703** [comment]
It been more than a week can you now assign this task to me @Spyware007

**Comment by Spyware007** [comment]
@abhi03ruchi Are you working on this?
or should I reassign it to someone else??

**Comment by abhi03ruchi** [comment]
Yes, will submit it by today.

**Comment by Spyware007** [comment]
@abhi03ruchi Okay sure!
Otherwise I have to assign it to someone else!
