### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by sumitkr2000** [GrabBits/GrabBits_Website#15]
Hey @Spyware007 I want to add the steps for contribution in the readme file. Please assign me this issue so that I can start working on this issue. Thank you!

**Comment by Spyware007** [comment]
@sumitkr2000 Assigned to you.
Make sure there are some other issues like this so don't fall into conflicts.
All the best.

**Comment by sumitkr2000** [comment]
@Spyware007 yeah sure bro. Thank you!

**Comment by kuvamdazeus** [comment]
Closing this issue as the CONTRIBUTION.md was created in a PR by someone else, feel free to create a new issue if needed :)
