### ISSUE TITLE
[Feat]: Add Skeleton screen animation to Opportunities page.

### ISSUE THREAD

**Issue by harmeetsingh11** [GrabBits/GrabBits_Website#154]
## Feature 

Since the API takes some time to fetch jobs on Opportunities page ,now we have only a loader animation that's looking basic we need to improve.
Using react-Ioading-skeleton library, I will add a skeleton screen animation to opportunities page it will be more engaging for users.

### Current
![before](https://github.com/GrabBits/GrabBits_Website/assets/130365071/96f573f3-ad7d-41e6-b95e-6bb696e4dcb4)

### After the implementation of this feature
![skeleton loading](https://github.com/GrabBits/GrabBits_Website/assets/130365071/f9ffddea-1794-4c05-8694-2ba96f2bb7d3)

### Record
- [x] I agree to follow [Contributing Guidelines](https://github.com/GrabBits/GrabBits_Website/blob/8718f5d3ae6c90e7fd7391f508cccd0e6978560a/CONTRIBUTING.md) and [Code of conduct](https://github.com/GrabBits/GrabBits_Website/blob/8718f5d3ae6c90e7fd7391f508cccd0e6978560a/CODE_OF_CONDUCT.md)
- [x] I'm a GSSoC'23 Contributor
- [x] I want to work on this issue 

Please assign me this issue under GSSoC'23
Thanks

**Comment by Bhushan8177** [comment]
Hey @harmeetsingh11 ,  I guess skeletal animation does not fit right for now, can we go for a cool loader instead, I think that would look more pleasing , what do you say !

**Comment by harmeetsingh11** [comment]
Yes. That sounds good @Bhushan8177, I will try to improve the loader. Do you want me to use any additional react library or simply go with Vanilla CSS?

**Comment by Grab-Bits** [comment]
> Contributor

anything would work, just it should look out of the box !!
