### ISSUE TITLE
[FEATURE] Adding pre loader page 

### ISSUE THREAD

**Issue by ManishaSwain8** [GrabBits/GrabBits_Website#155]
As the variety of features will go on adding ,the loading time will increase so it fair deal to add a preloader page to improve user engagement .
If this feature is required ,do assign it to me under GSSOC 2023!
Changes will be done in no time !  : |)

**Is your feature request related to a problem? Please describe.**
Kindly provide a comprehensive explanation of the problem or challenge that your feature request aims to resolve. Please detail any frustrations, limitations, or inefficiencies you currently encounter in relation to this problem.

**Describe the solution you'd like**
Please present a concise and precise description of the solution you envision. Clearly articulate the specific functionality or outcome you anticipate from the proposed feature.

**Describe alternatives you've considered**
Elaborate on any alternative solutions or features that you have already evaluated as potential approaches to address the problem at hand. Include a succinct evaluation of their respective advantages and disadvantages in comparison to your desired solution.

**Additional context**
Include any supplementary information, contextual details, relevant screenshots, or supporting materials that can aid in better understanding and supporting your feature request.

**Comment by Bhushan8177** [comment]
Go ahead @ManishaSwain8 , Best of luck !!
