### ISSUE TITLE
[bug]: GitHub Action workflow not working

### ISSUE THREAD

**Issue by harmeetsingh11** [GrabBits/GrabBits_Website#158]
**Describe the bug**
The GitHub Action greetings workflow is not working. We need to fix it.

**Location of the bug**
.github/workflows/greetings.yml

**Expected behavior**
The github action greeting workflow should greet when new PR/issue opens.

**Screenshots**
![Capture](https://github.com/GrabBits/GrabBits_Website/assets/130365071/54c5a341-2189-410b-b2d8-e7feac77c43c)

Please assign me this issue under GSSoC'23.
Thanks.

**Comment by Bhushan8177** [comment]
Go ahead @harmeetsingh11 , assigning it to you !!
