### ISSUE TITLE
"Frequently Asked Questions" Section Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [GrabBits/GrabBits_Website#164]
### Is your feature request related to a problem? Please describe.
No. It's an enhancement in the existing design.

### Describe the solution you'd like
The interface of this section is really nice but it can be improved by making some design adjustments. Working on the content alignment of this section, I can make it look even better which will eventually improve the overall website design.

### Describe alternatives you've considered
Content and form alignment

### Additional context
**Current Design**
![grabbit (2)](https://github.com/GrabBits/GrabBits_Website/assets/115794049/b602a746-3861-46ef-9b3d-7fa9e6d8f0b6)

**Expected Updated Design**
![grabbit (1)](https://github.com/GrabBits/GrabBits_Website/assets/115794049/2ffa10a7-1f18-40f6-afed-f7ee914c6367)

**Comment by Bhushan8177** [comment]
Hey @iamRabia-N , Sorry but I think the above change doesn't add a significant value to the design , I hope you get it !!
you can go for other issues or create a more valuable issue of your own !!
