### ISSUE TITLE
Implement lazy loading to the pages

### ISSUE THREAD

**Issue by Avinash905** [GrabBits/GrabBits_Website#167]
**Is your feature request related to a problem? Please describe.**
Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience.

The benefits of lazy loading include:

- Reduced initial load time
- Improved user experience
- More responsive website

**Describe the solution you'd like**
I would like to add lazy loading to the website for a better user experience.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Bhushan8177** [comment]
Hey @Avinash905 , Great idea would surely like to implement this, Assigning you !!

**Comment by Avinash905** [comment]
Please add the labels also

**Comment by Bhushan8177** [comment]
I will add that in the pr @Avinash905 , no worries!!
