### ISSUE TITLE
Link Explore button on website to https://www.youtube.com/@grabbits_

### ISSUE THREAD

**Issue by sabhisharma-ise** [GrabBits/GrabBits_Website#17]
Issue: There is an unlinked button on the website that does not do anything when clicked.

Solution: We propose to add a link to the button that will take users to the following URL:
https://www.youtube.com/@grabbits_

Benefits: Adding a link to the button will make it easier for users to access the information that they are looking for. It will also make the website more user-friendly and accessible.

I hope this helps!

Contributor - Sabhi Sharma (GSSOC'23)

**Comment by Spyware007** [comment]
@sabhisharma-ise Similar Issue is created.
