### ISSUE TITLE
Bug in Search bar

### ISSUE THREAD

**Issue by Monson2002** [GrabBits/GrabBits_Website#171]
**Describe the bug**
There is a bug in the search bar of the "Opportunities" section. When a user types in a string in the search bar in all lowercase, many times it won't return anything, even if it is returned by the API, because the API has stings in snake case.

**Expected behavior**
I've added a function which will capitelize the first letter of the passed argument into the search bar which will improve the searching in "Opportunity" section. Refer the videos to better understand the proposed changes. 

**Videos**
**Before**

https://github.com/GrabBits/GrabBits_Website/assets/91113152/171e3fd9-b7c5-415c-9023-ebcc10b36ec6

**After**

https://github.com/GrabBits/GrabBits_Website/assets/91113152/ff0192cd-10f1-4131-8033-3bccfec427a8

**Additional Content**
I'd like to work on this @Bhushan8177 UNDER gssoc'23.

**Comment by SaurabhBarde-007** [comment]
Great Video @Monson2002 , Assigning you under Gssoc!!

**Comment by Deepanshu0703** [comment]
@SaurabhBarde-007  can you assign this issue to me

**Comment by SaurabhBarde-007** [comment]
Hello Deepanshu ,
 I assigning you under gssoc'23, for this issue try to implement it using useMemo hook also try to keep search bar steady while searching .

**Comment by SaurabhBarde-007** [comment]
Hello Deepanshu ,
I am assigning you under gssoc'23, for this issue try to implement it using useMemo hook also try to keep search bar steady while searching .

**Comment by SaurabhBarde-007** [comment]
Hello @Deepanshu0703 ,
I am assigning you under gssoc'23, for this issue try to implement it using useMemo hook also try to keep search bar steady while searching .

**Comment by Deepanshu0703** [comment]
Ok I am implementing it using usememo assign it to me @SaurabhBarde-007

**Comment by SaurabhBarde-007** [comment]
Assigned to you @Deepanshu0703
