### ISSUE TITLE
Adding a sitemap to the website

### ISSUE THREAD

**Issue by mukul314** [GrabBits/GrabBits_Website#175]
**Is your feature request related to a problem? Please describe.**
Currently there is no site map for the website, having a sitemap is essential for the website. For example, Google largely finds webpages through links. And if the site is brand new and only has a handful external backlinks, then a sitemap is HUGE for helping Google find pages on your site.

**Describe the solution you'd like**
I will use a normal XML sitemap in the webiste that will boost it's seo performance.

**Describe alternatives you've considered**
None
**Additional context**
@Bhushan8177 , I'd like to work on this issue under gssoc'23

**Comment by Bhushan8177** [comment]
Great job @mukul314 , assigning you Best of Luck !!

**Comment by mukul314** [comment]
> Hey @mukul314 , i would like to know he update on this issue!!

Sorry for the delay, I'll do asap.
