### ISSUE TITLE
Links missing for redirect on main page

### ISSUE THREAD

**Issue by afeefuddin** [GrabBits/GrabBits_Website#177]
**Describe the bug**
Please provide a clear and concise description of the issue encountered, including any relevant details about the bug.
On the main page in the section shown in image 
Oppurtunities grab them should redirect to oppurtunites page on clicking 
Similar with other 
![Screenshot (25)](https://github.com/GrabBits/GrabBits_Website/assets/126336384/28528290-2a08-4791-8857-61d4193346b5)

**Location of the bug**
If known, please specify the file location where the bug was identified, including any relevant directories or paths.
Main page

**Comment by afeefuddin** [comment]
Can you please assign the issue to me under gssoc 23

**Comment by Bhushan8177** [comment]
Great obervation @afeefuddin , assigning you , go ahead !!
