### ISSUE TITLE
Website does not have proper meta tags

### ISSUE THREAD

**Issue by Avinash905** [GrabBits/GrabBits_Website#187]
**Is your feature request related to a problem? Please describe.**
The website does not have meta tags with descriptions. This means that the website is not as visible in search results, and users are less likely to click on the website's links.

**Describe the solution you'd like**
The website should contain important meta tags. This will help the website rank higher in search results and attract more visitors.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Bhushan8177** [comment]
Great @Avinash905 , Go ahead !!
