### ISSUE TITLE
Adding dependabot.yml

### ISSUE THREAD

**Issue by Anshika-Jain02** [GrabBits/GrabBits_Website#189]
*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

@Bhushan8177 please assign me this issue under gssoc'23.

**Comment by Bhushan8177** [comment]
Great observation @Anshika-Jain02 , assigning you this best of luck!!
