### ISSUE TITLE
[ISSUE] Overflowing content

### ISSUE THREAD

**Issue by DivyanshiNarang** [GrabBits/GrabBits_Website#191]
Content overflowing 

<img width="879" alt="Screenshot 2023-06-16 233449" src="https://github.com/GrabBits/GrabBits_Website/assets/74779601/0788a600-b120-48b8-b075-d07172e3741f">

*Please assign this issue to me under GSSoC'23* @Bhushan8177

**Comment by Bhushan8177** [comment]
Hey @DivyanshiNarang , Thanks for the advice but the design is meant for the overflow !!
You can go for other issues meanwhile
