### ISSUE TITLE
Contact Us Form Different Look on Large Screens 

### ISSUE THREAD

**Issue by iamRabia-N** [GrabBits/GrabBits_Website#194]
**Describe the bug**
Contact us form is looking as desired on normal screen but on large screen, its textboxes styling changes.

**Location of the bug**
"Contact" button on navbar -> Contact us form
To test it on leptop/computer screen, do zoom out and you'll see the difference.

**Expected behavior**
Same styling on all screens.

**Screenshots**
Two different behaviors of form.
![grabbits](https://github.com/GrabBits/GrabBits_Website/assets/115794049/8de94ab8-b327-4eed-bf12-17eec3fb2557)
![grabbits (1)](https://github.com/GrabBits/GrabBits_Website/assets/115794049/4665457d-a8c1-4d93-9ded-d9491831177e)

**Additional context**
N/A

**Comment by Grab-Bits** [comment]
Hey @iamRabia-N , I don't see any issues in that, can you please eloborate a bit because after zooming out , the content tends to misplace as per normal behaviour !!

**Comment by iamRabia-N** [comment]
@Grab-Bits  The misplacement of "Name, Email, Mobile Number, Message" input areas to very right side

**Comment by Spyware007** [comment]
@iamRabia-N Oh okay You can start fixing it!
