### ISSUE TITLE
{GSSoC'23] Improve text of 'Who We Are' section

### ISSUE THREAD

**Issue by poorvijn** [GrabBits/GrabBits_Website#208]
I think we could improve the text of the Who We Are section by making the following changes:

1. Change the incorrectly spelled name of Grab bit to GrabBit.
2. Remove the two dots at the end of each sentence and structure the sentences in a better way.
3.  Add a tagline, like GrabBit is a community of the students, by the students, and for the students.

Here is how it appears right now:
![text](https://github.com/GrabBits/GrabBits_Website/assets/87180220/1a7efde6-328b-4a03-8d95-6236a6936ca9)

If this sounds like a good idea, could you please assign it to me under GSSoC'23?

**Comment by Grab-Bits** [comment]
Hey @poorvijn , Sorry but I don;t find it adding value for now, you can go for other issues!
