### ISSUE TITLE
[style]: Hover effect to Highlights (infinite scroll )in Tickets section.

### ISSUE THREAD

**Issue by ManishaSwain8** [GrabBits/GrabBits_Website#209]
### What's the style idea?

 Even though there is on-hover:pause in this section ,when the user hover on it they may get confused whether it is clickable on not , So just adding  hover effect on each card in ticket section will be fair enough.
If this change required do assign under GSSOC 2023. !

### Add screenshots

Add screenshots,Example below..
![Screenshot (79)](https://github.com/GrabBits/GrabBits_Website/assets/96622693/f719d828-bef6-4f40-9e9a-4e8adc089b4e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Grab-Bits** [comment]
Hey @ManishaSwain8 , Great observation but I don't think this will add more value to the project.
Meanwhile you can go for other issues !!

**Comment by ManishaSwain8** [comment]
Yup make sense 😅 @Grab-Bits
