### ISSUE TITLE
Add lazy loading 

### ISSUE THREAD

**Issue by sumitkr2000** [GrabBits/GrabBits_Website#216]
**Is your feature request related to a problem? Please describe.**

Hey, I want to add lazy loading to the website. The benefits of lazy loading include:

- **Reduces initial load time –** Lazy loading a webpage reduces page weight, allowing for a quicker [page load time].

- **Bandwidth conservation –** Lazy loading conserves bandwidth by delivering content to users only if it’s requested.

- **System resource conservation –** Lazy loading conserves both server and client resources, because only some of the images, Jav
- Implement lazy loading

**Describe alternatives you've considered**
Elaborate on any alternative solutions or features that you have already evaluated as potential approaches to address the problem at hand. Include a succinct evaluation of their respective advantages and disadvantages in comparison to your desired solution.

**Additional context**
Include any supplementary information, contextual details, relevant screenshots, or supporting materials that can aid in better understanding and supporting your feature request.

**Comment by Bhushan8177** [comment]
Hey @sumitkr2000 , We have already implemented it , you can go for other issues !!

**Comment by sumitkr2000** [comment]
Okay...when I raised this issue it was not implemented. It's ok!
