### ISSUE TITLE
Issues Template

### ISSUE THREAD

**Issue by parasss19** [GrabBits/GrabBits_Website#220]
### Issue 1
- Right now in issues template bug and feature files are in .md format whereas style file is in .yml format
<img width="946" alt="Screenshot 2023-06-25 141655" src="https://github.com/GrabBits/GrabBits_Website/assets/101205226/a389d8b0-5f4e-4d5a-b828-523dceb2001e">

### Issue 2
- Issues template also doesn't have checkboxes  which are very helpful for project admins to label the issues.

### Resolved issue 1 
- I will write proper .yml code for all the issues template files so that all files are in .yml format and also yml format files looks better than .md files (below is the sample)
<img width="721" alt="temp img" src="https://github.com/GrabBits/GrabBits_Website/assets/101205226/a109772f-7472-450a-a583-38ae7c3da035">

### Resolved issue 2 
- I will add checkboxes so that it would be easy for you to label the issues (below is the sample)
<img width="640" alt="Screenshot 2023-06-20 233055" src="https://github.com/GrabBits/GrabBits_Website/assets/101205226/c502ddbf-66a7-4822-be59-076b15048955">

**Comment by parasss19** [comment]
Hi @Bhushan8177 Please review it

**Comment by Bhushan8177** [comment]
Hey @parasss19 , I guess the current system works fine, there is no need of changes !!
till then you can go for other issues !!
