### ISSUE TITLE
Real-time-validation in Contact

### ISSUE THREAD

**Issue by AlfiyaSiddique** [GrabBits/GrabBits_Website#223]
**Is your feature request related to a problem? Please describe.**
Currently, there is no validation in the contact form any kind of data can be sent. I want to implement real-time Validation in contact form similar to the below one:

https://github.com/UBA-GCOEN/StichHub/assets/86224794/1781b237-b885-40e3-ad5a-89694ca4b355
 

**Describe the solution you'd like**
I would use react states and implement real-time validation messages and also prevent the form from submission with invalid inputs and errors.

** Issue Image **

<img width="564" alt="5" src="https://github.com/GrabBits/GrabBits_Website/assets/86224794/6a89df75-1f89-424d-b4bf-c84939f996d4">

**Constraints**
Following constraints can be implemented in the respective fields:
Name: min 6 characters
Email: Valid Regex
phone: Valid Regex
Message: Minimum 10 words and Max 50
Let me know if you want to change above constraints

 **Request** 
Please assign me this issue under gssoc23 label

**Comment by Bhushan8177** [comment]
Nice observation @AlfiyaSiddique , Assigning you !
