### ISSUE TITLE
[new Feature] : Adding contributors list

### ISSUE THREAD

**Issue by Bhuvanchand26** [GrabBits/GrabBits_Website#229]
In the About page, we have our creative crew, I feel like in About page having contributors would look great as this is an open-source project.
Generally, the contributors are included as a grid, but as we have only a small amount of space. It would be good to make the contributors list a carousel (or as grid ).
I've worked on the carousel before. So I'm confident that I can do this
Please assign me this issue under GSSoC'23

**Comment by Bhushan8177** [comment]
Hey @Bhuvanchand26 , Currently we don't think it is proper time to add contributors grid, lets see if we change our mind !!
