### ISSUE TITLE
[style]: Remove inconsistency in style

### ISSUE THREAD

**Issue by Prajwal0225** [GrabBits/GrabBits_Website#231]
### What's the style idea?

Here is some inconsistency in this section Recousese card got out of the box

### Add screenshots

Add screenshots

![image](https://github.com/GrabBits/GrabBits_Website/assets/103810119/70d8e8ce-83f1-409d-9a6c-0a17a8e2aef9)

Can you please assign this issue to me? So that I can start working on it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bhushan8177** [comment]
Hey @Prajwal0225 , it is as per the design only , meanwhile you can go for other issues !
