### ISSUE TITLE
Text enhance 

### ISSUE THREAD

**Issue by shraddha761** [GrabBits/GrabBits_Website#234]
The text which is show in FAQ look uneasy 
![image](https://github.com/GrabBits/GrabBits_Website/assets/106100728/400f6cb9-6425-4364-b08d-86de6fb61ea5)

We can either change color and increase size.
Assign this issue to me under GSSOC'23

**Comment by Bhushan8177** [comment]
Hey @shraddha761 , I think currently we don't think there is any change required in the faq section , you can go for other issues !!
