### ISSUE TITLE
[style]: change the appearance of homepage

### ISSUE THREAD

**Issue by linga66** [GrabBits/GrabBits_Website#236]
### What's the style idea?

We need to improve the appearance of the homepage by changing the blocks of the dream job section

### Add screenshots

![Screenshot (718)](https://github.com/GrabBits/GrabBits_Website/assets/103192975/2ca77649-1d1b-4210-8ff7-c9c280f9c3a0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bhushan8177** [comment]
Hey @linga66 , the design is made to look that way only Meanwhile you can go for other issues !!
