### ISSUE TITLE
[BUG] Transition of Contact Us box heading even when there is text inside

### ISSUE THREAD

**Issue by Sar-thak-3** [GrabBits/GrabBits_Website#237]
**Describe the bug**
The heading inside the Contact Us box is showing transitions even when there is text inside due to which both text overlaps and doesn't seems good. Some of the inputs are already aligned this way but "Your query" and "Email" inputs are remaining.

**Location of the bug**
Contact Us box in "/Home" and "/Contact".

**Expected behavior**
When there is text inside no transition occurs!

**Screenshots**
![image](https://github.com/GrabBits/GrabBits_Website/assets/100359818/8be661e8-7b82-42e2-88eb-cd51e7ea7fcc)

If you find the issue relevant, Kindly assign me under GSSoC 2023!

**Comment by Bhushan8177** [comment]
Great observation @Sar-thak-3 , Assigning you !!
