### ISSUE TITLE
Resources Card is Overflowing on the screen

### ISSUE THREAD

**Issue by crocmons** [GrabBits/GrabBits_Website#239]
Resources Card is Overflowing on the screen .. I want to fix it.. Kindly assign this issue to me as a GSSOC23 contributor.

![Screenshot (466)](https://github.com/GrabBits/GrabBits_Website/assets/106610322/f031bd77-8be4-47bd-bdba-1d3660733246)

**Comment by Bhushan8177** [comment]
Hey @crocmons , that is the design we have thought of , looks different but yeah we work somewhat differently !!
Meanwhile you can go for other issues !!
