### ISSUE TITLE
GitHub Templates to open issue, suggest new features etc.

### ISSUE THREAD

**Issue by tuhinaww** [GrabBits/GrabBits_Website#24]
Hey, We can have GitHub template so that new contributors can open issue, suggest changes, report bugs in more descriptive way. It would be beneficial for mentors and well as the contributors.

If you want, I can work on this. Please assign this issue to me.

Thank you.

**Comment by medoubletea** [comment]
I am from GSSoC'23 btw.

**Comment by Bhushan8177** [comment]
Assigning it to you @medoubletea , Addition to what you said we will need template for instructions on how to run this project on their local as well as how they can contribute to issues or making their new issues

**Comment by medoubletea** [comment]
Thanks alot! I'll start working on it
