### ISSUE TITLE
[style]: Responsive Navbar

### ISSUE THREAD

**Issue by Neha5679** [GrabBits/GrabBits_Website#240]
### What's the style idea?

We need to improve  the Navbar as we scroll down we can't see the Navbar-section. I would like to improve it so please assign me.

### Add screenshots

Add screenshots
![Screenshot (81)](https://github.com/GrabBits/GrabBits_Website/assets/129548970/b6ce1dd9-f525-44ed-bdcc-f61f26bc5625)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bhushan8177** [comment]
hey @Neha5679 , The issue is fixed already, you can go for other issues till then !!
