### ISSUE TITLE
Uneven cards of Current Podcast

### ISSUE THREAD

**Issue by Tisha6661** [GrabBits/GrabBits_Website#245]
**Describe the bug**
The current podcasts cards are getting uneven according to the content in them.

**Location of the bug**
On Podcast Page

**Expected behavior**
I would like to fix the card style to keep it even, regardless of the content in it.

**Screenshots**
![image](https://github.com/GrabBits/GrabBits_Website/assets/98682478/e107d937-9083-4f04-9818-e5acc9f232a5)

**Comment by Bhushan8177** [comment]
Great observation @Tisha6661 , Assigning you !!
