### ISSUE TITLE
Add contribution guidelines to GitHub Repo

### ISSUE THREAD

**Issue by sabhisharma-ise** [GrabBits/GrabBits_Website#27]
Would love to add the Contribution Guidelines to the Readme.md file.
For Encouraging Contributors to the contribute to the repo!

Contributor - Sabhi Sharma (GSSOC'23)

**Comment by Bhushan8177** [comment]
Assigning you @sabhisharma-ise , Good Luck !!

**Comment by Bhushan8177** [comment]
I merged the pr but can you add to write proper comments so that I can get clear idea on what they want to contribute
