### ISSUE TITLE
Revamp of the Opportunities section

### ISSUE THREAD

**Issue by RashakDude** [GrabBits/GrabBits_Website#29]
Hey @Bhushan8177 

I was thinking of revamping the Opportunities section to resemble Devpost hackathons. 

<img width="70%" alt="Screenshot 2023-05-21 at 8 44 16 PM" src="https://github.com/GrabBits/GrabBits_Website/assets/45696541/4a6bb97b-5b11-4ab6-a37a-16cd4b36e08c">

This should look like this. This will be a major revamp so I suggest you add one or more contributors in this as well.
This also requires a change in the response from the backend API. 

Suggested features - 

- Sorting on the basis of Most Relevant, Most Recent and Total Amount
- Left panel filter of online or remote
- Filter of Full time, part-time, intern and hackathon

Thanking you, 
Rajat

**Comment by Bhushan8177** [comment]
@RashakDude it will be a great feature to add filters and sorting , but the UI of the card can  be better I think , if you can work on it I can assign it to you

**Comment by RashakDude** [comment]
@Bhushan8177 Please assign it to me

**Comment by Grab-Bits** [comment]
@RashakDude  What are your updates on this?

**Comment by RashakDude** [comment]
@Grab-Bits Working on it. Will update you by EOD.

**Comment by kuvamdazeus** [comment]
Hey @RashakDude 

Let us know if you're working on this, maybe share some SS of progress you've made so far here in this thread :)
