### ISSUE TITLE
Inconsistent font over the website

### ISSUE THREAD

**Issue by harshalwasnik22** [GrabBits/GrabBits_Website#30]
Title: Inconsistent font over the website

Description:

I've noticed that the font on the website is inconsistent. Some pages use apple-system, while others use Poppins (About Us) . This is causing a jarring user experience and is making it difficult to read the content.

Expected behavior:

- All pages should use the same font.

Actual behavior:

- Different pages use different fonts.

Possible solutions:

- Set a default font for the website.

Thanks for your time!

**Comment by bhushan-resoluteai** [comment]
Hey @harshalwasnik22 , we need this for now but will surely look into if we need a consistent font after a while
