### ISSUE TITLE
Changing the UI of the Opportunities page on large screen size devices (giving user better experience)

### ISSUE THREAD

**Issue by Lobi29** [GrabBits/GrabBits_Website#36]
![10](https://github.com/GrabBits/GrabBits_Website/assets/108052802/7dde13b7-2560-47a2-beff-c45d3fabb6e1)

### **ISSUE :** 

There's a large void section between the Job content and Job status (right click), which is unnecessary for the site.
And whenever somebody hover over the search icon -> Job, Intern, hackathon button displace itself automatically which is also unnecessary.

### **SOLUTION**
![9](https://github.com/GrabBits/GrabBits_Website/assets/108052802/09227756-34f3-4ea5-95e3-0afdc74ac20b)

I will change the UI of the site to this figma design, which will be more efficient for the opportunities page

Please assign this issue to me under @GSSOC2023

**Comment by kuvamdazeus** [comment]
Hi @Lobi29 

Please check issue #29 

Your issue seems very similar to this one.

The person who opened this issue can use some help from other devs as it is a pretty big one.
