### ISSUE TITLE
scroll up button 

### ISSUE THREAD

**Issue by Rajatkumarbehera11** [GrabBits/GrabBits_Website#40]
There is no scroll up button in every page , I can add a good looking and working scroll up button which will look better to the website,
I am a GSSOC'23 contributor assign this task to  me

**Comment by abhinav-m22** [comment]
@Rajatkumarbehera11 @kuvamdazeus 
Is this task completed?
I want to work on this issue if it is not completed yet

**Comment by kuvamdazeus** [comment]
Hey @abhinav-m22 
Actually, a new similar issue was assigned to someone else,

Please find another issue to work on or create one!
