### ISSUE TITLE
New page containing Resources for the students with a great UI

### ISSUE THREAD

**Issue by Bhushan8177** [GrabBits/GrabBits_Website#43]

**Comment by tusharv01** [comment]
Hi, @Bhushan8177 Please assign me this issue as my skills are aligned for solving this issue.

**Comment by Spyware007** [comment]
@tusharv01 @Ayushparui 
Are you going to work on this issue?

**Comment by tusharv01** [comment]
I will start to work from today as I am little busy.

**Comment by Spyware007** [comment]
@Ayushparui @tusharv01 
I am assigning this to both of you.
Collaborate and work together!

**Comment by tusharv01** [comment]
ok i will make changes soon.

**Comment by tusharv01** [comment]
@Ayushparui Can you please suggest to me what new changes should be done in the pre-existing figma file you send or I make it from scratch?

**Comment by Ayushparui** [comment]
@tusharv01 I'm not great at designing, it's up to you whether you want to create it from scratch or not but I want to mention that add courses, notes, certifications these references will be great if added, I'm not sure about the Blogs Bhushan mentioned whether a user will be creating blogs on the platform, if you are creating from scratch share the figma design file as well.

**Comment by tusharv01** [comment]
@Ayushparui  I have created a Design In figma https://www.figma.com/file/4Lg2R1XclfOjbhFbXeX4fB/UI?type=design&node-id=0%3A1&t=jRnRp3crW2C8blV0-1 
Not contains blog section until now? 
is design ok ?

**Comment by Ayushparui** [comment]
@tusharv01 I have some suggestions don't rush creating everything at the same time take your time and I'll be sharing with you some references on designing I'm not proficient at it, but it will help you in deciding.

The radial gradient you have used for the background is great.

These are for references : https://github.com/Ayushparui/Designs

There's a website https://lexica.art/ you can take help from here if you want.

**Comment by Ayushparui** [comment]
Hi @tusharv01 if you need any help connect with me on Discord, it will be better my discord username: _.Lee._#1071

**Comment by tusharv01** [comment]
I have started work on it and in between if I need any help then I will contact you.
Thankyou for offering the help.

**Comment by tusharv01** [comment]
@Ayushparui  https://www.figma.com/file/psO4lb4fIDGRMgdl8kvQO3/UI%2FGS?type=design&node-id=0%3A1&t=McZzC6m7Gwpg6bAf-1   
Please have a look on this,  not added blogs section till now.

**Comment by Ayushparui** [comment]
HI @tusharv01 it's great that you gave your time into making this, you need to give more time and efforts into making designs. I have created a design https://www.figma.com/file/yY7ZHkh6bHqiZmY2K4PAnp/Resources?type=design&node-id=0%3A1&t=N2fLi8eqHtKnuVFu-1 

@Spyware007 I have created a hero section for the resources page have a look at it. Let me know your feedback.

**Comment by tusharv01** [comment]
@Ayushparui Can you please tell me what type of design really merge-worthy as it gives me an idea of how the final design should i make?

**Comment by Ayushparui** [comment]
hello @tusharv01 can I know how much experience you have with UI designs,  below are some points which will help you in deciding about the final design

1. Hero Section which I have created above
2. A section which will give you an overview of what will be included in the resources page
3. Then we will follow accordingly like we'll be assigning every section for a particular resources like for blogs a dedicated section will be created will be creating a route which will take you to a particular page dedicated for only blogs.

**Comment by tusharv01** [comment]
I am new to UI designing

**Comment by Ayushparui** [comment]
@tusharv01 please head over to discord we can discuss further _.Lee._#1071 send me a friend request
