### ISSUE TITLE
transition delay in FAQ section

### ISSUE THREAD

**Issue by Lobi29** [GrabBits/GrabBits_Website#45]
### **ISSUE :** 
![17](https://github.com/GrabBits/GrabBits_Website/assets/108052802/6c947bd9-829a-459e-a67b-84fbfd1a56bc)

**1. Whenever user click on the plus(+) icon, content of that section comes instantaneously which gives a ugly impression to website.
There must be some delay ( transition -delay ) such that website gives the user a modern websites like experience**

**2. Design of FAQ is too common. So, it need to change to a better on**

### **SOLUTION :** 

**I will remove those issues** 

**Please assign these issues to me, under @GSSOC2023**

**Comment by Bhushan8177** [comment]
Great observation @Lobi29 , can you please be more specific how will you contribute

**Comment by Lobi29** [comment]
### **Figma design**
![21](https://github.com/GrabBits/GrabBits_Website/assets/108052802/36feba13-67a2-4d67-9d59-4a090cea4c1b)

**This is my Figma design and I want to implement this UI on your website.**
**If you agree with my design then please assign this feature upgradation to me. under @GSSOC2023**

**Comment by Spyware007** [comment]
@Lobi29  Assigned to you! Just use the contact form from the Contact us routes and change the styles only for homepage.
