### ISSUE TITLE
Adding Code of Coduct

### ISSUE THREAD

**Issue by parthpathakpp1** [GrabBits/GrabBits_Website#46]
Code of Conduct will have all the guidelines that should be followed by a Contributor.

**Comment by parthpathakpp1** [comment]
> Code of Conduct will have all the guidelines that should be followed by a Contributor.

Assign me this issue under GSSOC'23.

**Comment by Bhushan8177** [comment]
Great @parthpathakpp1 , Assigned you !!

**Comment by kuvamdazeus** [comment]
Hey @Bhushan8177 I think this issue for adding a Code of Conduct seems similar to issue #34 

I have already assigned someone to work on that.

So, this issue needs to be marked as duplicate...

**Comment by parthpathakpp1** [comment]
> Hey @Bhushan8177 I think this issue for adding a Code of Conduct seems similar to issue #34
> 
> I have already assigned someone to work on that.
> 
> So, this issue needs to be marked as duplicate...

 @kuvamdazeus I just made a PR. 😔

**Comment by kuvamdazeus** [comment]
No worries, give me a minute, let's see what can be done :)

**Comment by parthpathakpp1** [comment]
> No worries, give me a minute, let's see what can be done :)

ok

**Comment by kuvamdazeus** [comment]
I have merged your PR, but please keep in mind to search for keywords in the issues tab before you're opening an issue and confirm that no one's doing the same thing.

Thanks for the contribution.

**Comment by parthpathakpp1** [comment]
> I have merged your PR, but please keep in mind to search for keywords in the issues tab before you're opening an issue and confirm that no one's doing the same thing.
> 
> Thanks for the contribution.

okay ,sure will keep in mind .
