### ISSUE TITLE
FAQ Font Family

### ISSUE THREAD

**Issue by parthpathakpp1** [GrabBits/GrabBits_Website#47]
Font Family of FAQ section should be changed . It looks totally different from the other fonts of website. 
![grabbits](https://github.com/GrabBits/GrabBits_Website/assets/85991449/f2242b2f-ad1d-48f2-ab16-b54bdb4a2e33)

**Comment by parthpathakpp1** [comment]
> Font Family of FAQ section should be changed . It looks totally different from the other fonts of website. ![grabbits](https://user-images.githubusercontent.com/85991449/240220491-f2242b2f-ad1d-48f2-ab16-b54bdb4a2e33.png)

Assign me this issue under GSSOC'23.

**Comment by parthpathakpp1** [comment]
Assign me this issue under GSSOC'23

**Comment by Bhushan8177** [comment]
Hey @parthpathakpp1 , I think for now it isn't required , You can contribute to other issues !!
