### ISSUE TITLE
Refactoring "SERVER" folder structure.

### ISSUE THREAD

**Issue by Ayushparui** [GrabBits/GrabBits_Website#53]
### ISSUE in the folder Structure

The `config.js`  file is exposed to the root server folder making it vulnerable.

### TITLE

1. The aim of this PR is to Refactor the **SERVER** folder structure, by creating a separate **_Utils_** folder for referencing environment variables.

2. Changing the **_config_** folder name to **_database_** .

### USE

1. Centralized configuration management: Placing the configuration file within the utils folder allows for centralized management of environment variables used by utility functions or modules. It provides a convenient location to store and access environment-specific settings.

2. Code separation and modularity: By separating the configuration file from the rest of the codebase, you can isolate environment variable handling logic and keep it distinct from other utility functions or modules. This can enhance code modularity and make it easier to maintain and update the configuration.

3. Encapsulation of environment-specific details: Placing environment variables in a dedicated configuration file helps encapsulate environment-specific details from the rest of the code. It promotes cleaner code separation and allows developers to focus on the functionality of the utility functions without worrying about the specific environment settings.

4. Reusability and portability: Having a separate configuration file inside the utils folder makes it easier to reuse the utility functions or modules in different projects or environments. You can simply update the configuration file with the appropriate environment variables when deploying the code to a new environment, without modifying the underlying utility code.

Contributor from GSSOC'23 you can assign the issue after reading.

**Comment by Spyware007** [comment]
@Ayushparui Assigned to you.
Make sure you don't break the code!
