### ISSUE TITLE
Adding hover effect (Gssoc'23)

### ISSUE THREAD

**Issue by shwetazade27** [GrabBits/GrabBits_Website#56]
Hover effect can be added in Extra section on four boxes which will make it look more appealing
![418_new](https://github.com/GrabBits/GrabBits_Website/assets/84389800/b65d6daf-dec2-44e7-95d0-af771cc8c3a8)

**Comment by shwetazade27** [comment]
@kuvamdazeus sir I am facing this problem while running this project on my device .. Could you please provide some guidance on how to resolve this issue?
![421](https://github.com/GrabBits/GrabBits_Website/assets/84389800/1b019095-ebda-487f-a26e-3aae7b0ac7a6)

**Comment by kuvamdazeus** [comment]
checking, please wait

**Comment by kuvamdazeus** [comment]
Allow me to explain what's happening here

### Problem
Actually, there shouldn't be a package-lock.json file at the root of this repository,
We run npm-related commands in Javascript projects, like the client folder & server folder.

Here, when you're running the npm command, the npm program can't find a `package.json` file that consists of the dependencies that a project contains, but the root directory containing server & client is not REALLY a Javascript project, is it?

The client & server folders contain the JS projects, React app & node app respectively.
Therefore, npm-related commands like `npm i` or `npm run start` will only work there when running in those one of the folders.

### Solution
In your case, you're contributing in the frontend, thus follow these steps:

1. cd into the client folder
2. and then run the command you were trying to run

**Comment by shwetazade27** [comment]
@kuvamdazeus Yes Sir now it is working .. Thankyou so much for detailed explanation.

**Comment by shwetazade27** [comment]
@kuvamdazeus Sir .. does this means I have made a pull request or there any further steps after this? I have followed the steps given in contribution file ..
![422_new](https://github.com/GrabBits/GrabBits_Website/assets/84389800/545c6445-974d-42e9-8a3d-eda91c4760d4)
