### ISSUE TITLE
Adding Mail Link [GSSOC'23]

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [GrabBits/GrabBits_Website#65]
## Mail Link Add / Hover Effect

I want to add a link to the mail in the footer section of the page and also will be adding a slight hover effect to make it look good.

## Screenshots

![image](https://github.com/GrabBits/GrabBits_Website/assets/85278243/774670c0-5953-460a-b78d-1e8ee8b6b702)

Please assign me this issue under GSSOC'23

**Comment by kuvamdazeus** [comment]
Good observation, you can start working on it now :)
