### ISSUE TITLE
No Padding on contact form 

### ISSUE THREAD

**Issue by shobhitexe** [GrabBits/GrabBits_Website#71]
**Describe the bug**
Hey as seen in SS below there need to be some padding for contact form it will look more professional and clean that way 

**Location of the bug**
https://grabbits.vercel.app/contact

**Screenshots**
![image](https://github.com/GrabBits/GrabBits_Website/assets/29349136/b272c267-9123-4b0c-a7f4-e188c9b46991)

**Comment by kuvamdazeus** [comment]
@shobhitexe Do you want me to assign it to you?

**Comment by shobhitexe** [comment]
> @shobhitexe Do you want me to assign it to you?

Yes sure I would love to work on it
