### ISSUE TITLE
"Contact Us" Section Submit button Alignment

### ISSUE THREAD

**Issue by iamRabia-N** [GrabBits/GrabBits_Website#72]
**Is your feature request related to a problem? Please describe.**
No. It's not a problem but an enhancement in "Contact Us" form button alignment.

**Describe the solution you'd like**
Submit button on left aligned is conflicting with user's default perspective of action button in center. And also for design enhancement, the alignment of button is central will look good.

**Describe alternatives you've considered**
Submit button alignment in center rather than left-sided.

### Screenshots

**Current Alignment**
![gabbit ss (2)](https://github.com/GrabBits/GrabBits_Website/assets/115794049/3abd5455-4dc9-4eb2-a3bc-7f065b223531)

**Expected Updated Alignment**
![gabbit ss (1)](https://github.com/GrabBits/GrabBits_Website/assets/115794049/be30e413-2d30-43ed-a443-8800b8e9856b)

**Comment by kuvamdazeus** [comment]
Assigned it to you,
Also along with that, can you please correct the alignment of the question mark icon & "Contact Us" text in the PR?

**Comment by iamRabia-N** [comment]
Sure

> Assigned it to you, Also along with that, can you please correct the alignment of the question mark icon & "Contact Us" text in the PR?

**Comment by kuvamdazeus** [comment]
Closing the issue as the PR was merged
