### ISSUE TITLE
Add back-to-top buttons in content-rich pages

### ISSUE THREAD

**Issue by VSatwika** [GrabBits/GrabBits_Website#77]
- I would like to add back-to-top buttons to all the necessary pages so navigation is improved.
 - Could you assign this to me under GSSoC'23?

**Comment by kuvamdazeus** [comment]
Hey @VSatwika yeah I can assign this to you,
But could you please provide more details on how are you planning to add the back to top button in terms of:

1. Button design
2. Which Page(s)

Lets agree on these things first & then you can start working on it :)

**Comment by CYBWEBALI** [comment]
Could assign this issue to me?

**Comment by Deepanshu0703** [comment]
I have few designs and we can change the color on the basis of website design, few designs are given below

![image](https://github.com/GrabBits/GrabBits_Website/assets/114489502/b4febd6d-4321-4ca8-b510-d2ea35794b5e)

**Comment by Deepanshu0703** [comment]
@kuvamdazeus i want to contribute so if can assign it to me

**Comment by kuvamdazeus** [comment]
Hey @Deepanshu0703 
These designs look good you may start working on it, I'm re-assigning it to you

@CYBWEBALI please look into other issues or create one!
