### ISSUE TITLE
Toggle button is working in one way only

### ISSUE THREAD

**Issue by sumitkr2000** [GrabBits/GrabBits_Website#78]
**Describe the bug**
Hey, @kuvamdazeus The toggle buttons in the FAQ section are only working in one direction. I should open and close the questions but it is only opening it. I want to work on this issue. Please assign me this issue. Thank you!

**Location of the bug**
FAQ Section

**Expected behavior**
It should work in both direction

**Screenshots**
If applicable and available, please include screenshots that can help illustrate and clarify the problem.

**Additional context**
Please provide any additional context or information about the problem that may be helpful for understanding and resolving the bug.

**Comment by kuvamdazeus** [comment]
Good observation,
it is perfectly usable although misleading in terms of UX,
Assigning this to you!
