### ISSUE TITLE
Implement Debouncing for Search

### ISSUE THREAD

**Issue by AayushKrShukla** [GrabBits/GrabBits_Website#82]
**Is your feature request related to a problem? Please describe.**
Currently when we type in the search bar for every keystroke an API request is sent. 

**Describe the solution you'd like**
I would like to implement debouncing for the search field so that for everystroke a new api request is not made

**Describe alternatives you've considered**
We can also let the search request only be made after enter key is pressed or 

**Additional context**
https://github.com/GrabBits/GrabBits_Website/assets/56974422/e7dbd0bd-8e2b-4411-9e9a-b2ad11c1273f

**Comment by AayushKrShukla** [comment]
Can you please assign me this under `gssoc23` label?

**Comment by doppedheart** [comment]
good issue this will reduce the network load and can create a filter among the object responed and after enter key is pressed can create a new api fetch for the searched key word can also create the pagination for all the objects that is responded restricting it to limited number which further reduce the load size further optimizing the app

**Comment by doppedheart** [comment]
also wanted to help on this task , if you need some please just ask ..

**Comment by kuvamdazeus** [comment]
Great observation @AayushKrShukla 

Before I assign this issue to you, can you please tell me how are you planning to solve this problem?

Suggestions are welcome from @doppedheart too!

**Comment by Shubham-2899** [comment]
Hi @kuvamdazeus 
There are two approaches to solve this issue:
1-Making a Request After a Certain Delay:
This approach is suitable when real-time or continuous updates are required during user input. By introducing a delay of a certain number of milliseconds after the last keystroke, you can optimize the user experience by providing timely updates without overwhelming the server with excessive requests.

2-Making a Request After the Enter Key is Pressed:
This approach involves triggering the request only when the user presses the Enter key. It ensures that the user has finished providing input before initiating the request. 
If no one else takes up this issue, I am willing to work on it. Can help if needed

**Comment by AayushKrShukla** [comment]
@kuvamdazeus 

To solve this problem, I was thinking of  creating a reusable debounce function in the helpers folder. This function would accept two parameters: a target function and a delay. The purpose of the debounce function is to ensure that the target function is invoked the specific delay, and if the function is invoked again before that delay, the previous invocation is canceled.

**Comment by Bhushan8177** [comment]
great @AayushKrShukla , Assigned to you !!

**Comment by kuvamdazeus** [comment]
I'm also assigning @Shubham-2899 as his first point was spot-on & I think he might as well help @AayushKrShukla (if needed).

**Comment by AayushKrShukla** [comment]
Thank you for assigning me this issue.
Will create a PR soon.

Also would love to work together with @Shubham-2899 . We can connect on discord. My discord username BabyCheemz#6600
