### ISSUE TITLE
Input tags should be in centre 

### ISSUE THREAD

**Issue by Soulpurr** [GrabBits/GrabBits_Website#87]
The input tag of contact us section should be in centre they are in left which doesn't look great.

Screenshot -
![Screenshot_2023-05-27-16-14-00-58_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/GrabBits/GrabBits_Website/assets/92094765/918286d7-6644-40a2-a637-b2bda26ab501)

**Comment by Soulpurr** [comment]
Pls assign this to me under gssoc 23

**Comment by kuvamdazeus** [comment]
PR was merged, closing this issue.

Also, a quick tip @Soulpurr 

When making the PR, you can add this phrase anywhere in the description body of the PR:
```
Closes #<issue-number>
```

in your case:
```
Closes #87
```

This way, when the PR is merged, GitHub will automatically close the tagged issue too.

Thanks for your contribution!!

**Comment by Soulpurr** [comment]
Thanks next time I will keep it in mind
