### ISSUE TITLE
Card of contributors should be in centre 

### ISSUE THREAD

**Issue by Soulpurr** [GrabBits/GrabBits_Website#89]
These cards below in the screenshot are aligned to left they should be in centre.

Screenshot -
![Screenshot_2023-05-27-16-14-12-67_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/GrabBits/GrabBits_Website/assets/92094765/898b8f33-a863-4779-8041-e560d779cc0d)

 

Pls assign this to me under gssoc23

**Comment by Bhushan8177** [comment]
Assigned , Best of luck !!
