### ISSUE TITLE
No gap between Cards

### ISSUE THREAD

**Issue by shobhitexe** [GrabBits/GrabBits_Website#95]
**Describe the bug**
Hey as mentioned on SS attached below there is no gap between cards 

**Location of the bug**
https://grabbits.vercel.app/opportunities

**Expected behavior**
I think there should be some gap

**Screenshots**
![image](https://github.com/GrabBits/GrabBits_Website/assets/29349136/a023dc36-cecb-498f-8923-ab1fdef58464)

**Additional context**
You can assign this to me i would be very happy to create a PR Thanks

**Comment by Bhushan8177** [comment]
Hey, @shobhitexe , at the moment I don't think its necessary. 
You can surely check other issues, or create your own if you find something better , Best of Luck !!
Make to star the repository and Follow me !!
